---
clusters:
  - name: cluster1
    num_master: 3
    num_worker: 2
    vip: false
    master_base_vmid: 4000
    master_address_sans_last_octet: 192.168.0
    master_last_octet: 121
    master_gateway: 1
    master_domain: masters.home.lab
    worker_base_vmid: 5000
    worker_address_sans_last_octet: 192.168.1
    worker_last_octet: 131
    worker_gateway: 1
    worker_domain: workers.home.lab
