# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "opnsense" {
  type = object({
    uri          = string
    api_key     = string
    api_secret = string
  })
  sensitive = true
}
variable "proxmox" {
  type = object({
    api_url          = string
    api_token_id     = string
    api_token_secret = string
  })
  sensitive = true
}
