package types

// InternalData represents the internal data generated by the configuration generation process
type InternalData struct {
	Clusters []InternalDataCluster
}

// InternalDataCluster represents the data of a single cluster in the InternalData
type InternalDataCluster struct {
	Name    string
	Masters []InternalDataNode
	Workers []InternalDataNode
	Vip     bool
	Ha      bool
	HaIp    string
	HaFqdn  string
	SrvHa   bool
	SrvHaIp string

	AnsibleMasterGroup string
	AnsibleWorkerGroup string
}

// InternalDataNode represents the data of a generic node within a cluster
type InternalDataNode struct {
	Host       string
	Domain     string
	IP         string
	Gateway    string
	Nameserver string

	Core   int
	Memory int

	TerraformResourceName string

	ProxmoxVMID          int
	ProxmoxVmName        string
	ProxmoxVmDescription string
	ProxmoxVmTags        []string
}
