#!/usr/bin/env ansible-playbook
---
- name: Dynamically creates groups for {{ cluster_name }}
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add hosts to cluster_master group
      add_host:
        name: "{{ item }}"
        groups: cluster_master
      loop: "{{ groups[cluster_name + '_master'] }}"

    - name: Add hosts to cluster_worker group
      add_host:
        name: "{{ item }}"
        groups: cluster_worker
      loop: "{{ groups[cluster_name + '_worker'] }}"

- name: Setup {{ cluster_name }} cluster
  collections:
    - kubernetes.core
  hosts:
    - "cluster_master"
    - "cluster_worker"
  gather_facts: true
  become: true
  vars_files:
    - ../vars/all.yaml
    - ../vars/{{ k8s_distro }}.yaml

  roles:
    - cluster_setup
