#!/usr/bin/env ansible-playbook
---
- name: Setup {{ cluster_name }} cluster
  collections:
    - kubernetes.core
  hosts:
    - "{{ cluster_name }}_master"
    - "{{ cluster_name }}_worker"
  become: true
  
  roles:
    - rke2_setup
