---
- name: Create rke2 directories if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - '/etc/rancher/rke2/'
    - '/var/lib/rancher/rke2/server/manifests/'

- name: Configure rke2 registry mirrors (rimuovere?)
  ansible.builtin.template:
    src: 'registries.yaml.j2'
    dest: '/etc/rancher/rke2/registries.yaml'
    mode: '0755'
  when: registry_mirror
