---
- name: Ensure /etc/rancher/rke2 directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Define the content configfilecommon
  set_fact:
    configfilecommon:
      token: '{{ cluster_token }}'
      write-kubeconfig-mode: "0644"

- name: Define the content configfiletlsvip if vip present
  set_fact:
    configfiletlsvip:
      tls-san:
        - "{{ cluster_vip_fqdn }}"
  when: cluster_vip_fqdn is defined

- name: Define the content configfiletls
  set_fact:
    configfiletls:
      tls-san: "{{ groups['cluster_master'] | map('extract', hostvars, 'inventory_hostname') | list }}"

- name: Combine configfiletlsvip with configfiletls
  set_fact:
    configfiletls: "{{ configfiletlsvip | combine({'tls-san': configfiletlsvip['tls-san'] + configfiletls['tls-san']}) }}"
  when: cluster_vip_fqdn is defined

- name: Define the content configfileserver
  set_fact:
    configfileserver:
      server: "https://{{ groups['cluster_master'][0] }}:9345"

- name: Define the content configfileserver if vip present
  set_fact:
    configfileserver:
      server: "https://{{ cluster_vip_fqdn }}:9345"
  when: cluster_vip_fqdn is defined

- name: Define the content configfilemaster
  set_fact:
    configfilemaster:
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
      disable-cloud-controller: true

- name: Save the YAML content to a file on first master node
  copy:
    content: "{{ configfilecommon | combine(configfiletls) | combine(configfilemaster) | to_nice_yaml }}"
    dest: '/etc/rancher/rke2/config.yaml'
  when: inventory_hostname in groups['cluster_master'][0]

- name: Save the YAML content to a file on master 2 and 3
  copy:
    content: "{{ configfilecommon | combine(configfiletls) | combine(configfilemaster) | combine(configfileserver) | to_nice_yaml }}"
    dest: '/etc/rancher/rke2/config.yaml'
  when: inventory_hostname in groups['cluster_master'] and inventory_hostname != groups['cluster_master'][0]

- name: Save the YAML content to a file WORKER
  copy:
    content: "{{ configfilecommon | combine(configfileserver) | to_nice_yaml }}"
    dest: '/etc/rancher/rke2/config.yaml'
  when: inventory_hostname in groups['cluster_worker']