---
- name: Create rke2 directories if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - '/etc/rancher/rke2/'
    - '/var/lib/rancher/rke2/server/manifests/'

